github: push: upd
Signed-off-by: Daniel Gomez <da.gomez@samsung.com>

diff --git a/.github/workflows/push.yml b/.github/workflows/push.yml
--- a/.github/workflows/push.yml
+++ b/.github/workflows/push.yml
@@ -11,7 +11,7 @@ on:
       - '**'
 
 jobs:
-  push-pr:
+  pushpr:
     name: Push/PR kdevops CI
     uses: ./.github/workflows/main.yml
     secrets: inherit
@@ -21,9 +21,34 @@ jobs:
         ci_workflow:
           - blktests_nvme
           - xfs_reflink_4k
-    with:
-      ci_workflow: ${{ matrix.ci_workflow }}
-      kernel_ref: 'v6.15'
-      kernel_tree: 'linux'
-      test_mode: 'kdevops-ci'
-      tests: ''
+    steps:
+      - name: Checkout kdevops
+        run: |
+          set -euxo pipefail
+          git clone --verbose --progress --depth=1 \
+            --reference /mirror/kdevops.git \
+            $GITHUB_SERVER_URL/$GITHUB_REPOSITORY \
+            "kdevops-${{ github.run_id }}-${{ github.run_number }}"
+
+      - name: Symlink update
+        run: |
+          set -euxo pipefail
+          ln -sf \
+            "${{ github.run_id }}-${{ github.run_number }}" \
+            kdevops-run
+
+      - name: Checkout kdevops
+        uses: ./kdevops-run/.github/workflows/main
+        with:
+          ci_workflow: ${{ matrix.ci_workflow }}
+          dir: ${{ github.run_id }}-${{ github.run_number }}
+          kernel_ref: 'v6.15'
+          kernel_tree: 'linux'
+          test_mode: 'kdevops-ci'
+          tests: ''
+
+      - name: Cleanup workdir and symlink
+        if: always()   # ensure cleanup runs no matter what
+        run: |
+          rm -rfv "${{ github.run_id }}-${{ github.run_number }}"
+          rm -fv "kdevops-run"
